name: gpii-windows node tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      VCTargetsPath: 'C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140'
    steps:
      - uses: javihernandez/setup-node-nvm@input-arch-field
        with:
          node-version: "10.11.0"
          node-arch: "32"
          node-mirror: "https://nodejs.org/download/release/"

      - run: |
          node --version
          node -e "console.log(process.arch)"

      # - run: echo 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin' | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      # - run: echo $env:PATH
      # - run: npm config get prefix

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '2.7.17'

      - name: Install vcbuildtools
        run: choco install vcbuildtools -ia '/InstallSelectableItems VisualCppBuildTools_ATLMFC_SDK;VisualCppBuildTools_NETFX_SDK' -y
      - name: Install Windows 10 SDK
        run: choco install windows-sdk-10-version-1809-all --version=10.0.17763.1 -y
      - name: Install MS Build Tools
        run: choco install microsoft-build-tools -y
      - name: Install VisualCppBuildTools
        run: choco install visualcppbuildtools -y
      - run: npm config set msvs_version 2015 --global
      - run: npm config set python python2.7

      - run: npm install
      - run: node tests/UnitTests.js 

      # - run: echo $env:PATH
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '2.7.17'
      # - name: Install vcbuildtools
      #   run: choco install vcbuildtools -ia '/InstallSelectableItems VisualCppBuildTools_ATLMFC_SDK;VisualCppBuildTools_NETFX_SDK' -y
      # - run: echo $env:PATH
      # - name: Install Windows 10 SDK
      #   run: choco install windows-sdk-10-version-1809-all --version=10.0.17763.1 -y
      # - run: echo $env:PATH
      # - name: Install MS Build Tools
      #   run: choco install microsoft-build-tools -y
      # - run: echo $env:PATH
      # - name: Install VisualCppBuildTools
      #   run: choco install visualcppbuildtools -y
      # - run: echo $env:PATH
      # - name: Install nuget commandline
      #   run: choco install nuget.commandline -y
      # # This folder collides with nvm symlink folder
      # - run: echo $env:PATH
      # - run: npm config get prefix
      # - run: get-command node
      # - name: Rename default C:\Program Files\nodejs folder (disable default installation of Node.js)
      #   run: mv 'C:\Program Files\nodejs' 'C:\Program Files\nodejs-disabled'
      # - name: Install nvm
      #   run: choco install nvm -y
      # - run: echo $env:PATH
      # - name: Call refreshenv and update PATH
      #   shell: cmd
      #   run: |
      #     call refreshenv
      #     nvm install 10.11.0 32
      #     nvm use 10.11.0 32
      #     npm config set msvs_version 2015 --global
      #     npm config set python python2.7
      #     npm install
      #
      # - run: echo $env:PATH
      # - name: Install and setup Node.js 10.11.0 32bit
      #   run: nvm install 10.11.0 32 && nvm use 10.11.0 32
      # - run: echo $env:PATH
      # - run: npm config get prefix
      # - name: Finish Node.js set up
      #   run: |
      #     npm config set msvs_version 2015 --global
      #     npm config set python python2.7
      # - run: echo $env:PATH
      # - run: npm config get prefix
      # - run: get-command node
      # # Disabled temporary because it's rejecting to install
      # # - name: Install Grunt
      # #   run: npm install grunt-cli -g
      # - name: Run npm install
      #   run: |
      #     $env:PATH += ';C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\ProgramData\nvm\v10.11.0'
      #     echo $env:PATH
      #     Set-Alias node (Get-Command node).path
      #     npm install
      # - run: echo $env:PATH
      # - name: Run unit tests
      #   run: node tests/UnitTests.js
