name: gpii-windows node tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      VCTargetsPath: 'C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140'
    steps:
    - name: Install vcbuildtools
      run: choco install vcbuildtools -ia '/InstallSelectableItems VisualCppBuildTools_ATLMFC_SDK;VisualCppBuildTools_NETFX_SDK' -y
    - name: Install Windows 10 SDK
      run: choco install windows-sdk-10-version-1809-all --version=10.0.17763.1 -y
    - name: Install MS Build Tools
      run: choco install microsoft-build-tools -y
    - name: Install VisualCppBuildTools
      run: choco install visualcppbuildtools -y
    - name: Install nuget commandline
      run: choco install nuget.commandline -y
    - name: Install nvm
      run: choco install nvm -y
    - name: Install and setup node 12.19.0 32bit, run the tests
      shell: cmd
      run: |
        refreshenv
        nvm install 12.19.0 32
        nvm use 12.19.0
        npm config set msvs_version 2015 --global
        npm install grunt-cli -g
        npm install
        node tests/UnitTests.js
