name: gpii-windows node tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      VCTargetsPath: "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install vcbuildtools
      run: choco install vcbuildtools -ia "/InstallSelectableItems VisualCppBuildTools_ATLMFC_SDK;VisualCppBuildTools_NETFX_SDK" -y
    - name: Install Windows 10 SDK
      run: choco install windows-sdk-10-version-1809-all --version=10.0.17763.1 -y
    - name: Install MS Build Tools
      run: choco install microsoft-build-tools -y
    - name: Install VisualCppBuildTools
      run: choco install visualcppbuildtools -y
    - name: Install nuget commandline
      run: choco install nuget.commandline -y
    - name: Configure npm msvs_version
      run: npm config set msvs_version 2015 --global
    - name: Install grunt-cli
      run: npm install grunt-cli -g
    - name: Run npm install
      run: npm install
